language: php
php:
    - '7.1'
    - '7.2'
    - '7.3'

env:
    matrix:
        - DEPENDENCIES=--prefer-lowest
        -
cache:
    directories:
        - "$HOME/.composer/cache"

before_install:
    - alias composer=composer\ --no-interaction && composer selfupdate
    - composer global require hirak/prestissimo

install:
    - travis_retry composer update --no-progress --profile --no-scripts --no-suggest $DEPENDENCIES

script:
    - bin/symfony-grumphp install -q
    - bin/phpunit
    - vendor/bin/grumphp run
    - bin/symfony-grumphp install -q
    - bin/symfony-grumphp uninstall -q
