language: php
php:
    - 7.3
    - 7.4
    - 8.0

env:
    matrix:
        -
cache:
    directories:
        - "$HOME/.composer/cache"

before_install:
    - alias composer=composer\ --no-interaction && composer selfupdate

install:
    - travis_retry composer update --no-progress --profile --no-scripts --no-suggest && composer install

script:
    - bin/symfony-grumphp install -q
    - vendor/bin/grumphp run --testsuite=no-coverage
    - bin/symfony-grumphp install -q
    - bin/symfony-grumphp uninstall -q

after_success:
    - bin/symfony-grumphp install -q
    - vendor/bin/php-coveralls -v
